---
repos:
  - repo: https://github.com/szebenyib/pre-commit-pytest
    rev: 051fea3
    hooks:
      - id: pytest
        stages:
          - commit
        additional_dependencies:
          - pytest-black==0.3.12
          - pytest-flake8==1.0.7
          - pytest-isort==1.3.0
